name: Release and commentary

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.0'

      - name: Build avec le script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Test
        run: go test -v ./...

      - name: Stocker le binaire pour la Release
        uses: actions/upload-artifact@v4
        with:
          name: binary-artifact
          path: bin/aed

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Télécharger le binaire
        uses: actions/download-artifact@v4
        with:
          name: binary-artifact
          path: bin

      - name: Récupérer le message du commit
        id: get_message
        run: |
          # %B récupère tout le message (Sujet + Body)
          MSG=$(git log -1 --pretty=%B)
          
          # Astuce pour passer du texte multi-lignes à une variable d'environnement GitHub
          echo "COMMIT_MSG<<EOF" >> $GITHUB_ENV
          echo "$MSG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Créer la Release GitHub
        uses: softprops/action-gh-release@v2
        with:
          name: aed_${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          files: bin/aed
          body: |
            ## Version ${{ github.ref_name }}
            
            ${{ env.COMMIT_MSG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
